### ISSUE TITLE
Images for Website

### ISSUE THREAD

**Issue by CherryBeam** [CherryBeam/BusinessWebsite#1]
![Cherry Beam Logo Color](https://user-images.githubusercontent.com/90300147/132554204-50126ae5-8dac-410d-8fe7-85e416196d85.jpg)

![Cherry Beam Logo ColorTransparentBKG](https://user-images.githubusercontent.com/90300147/132555506-5330a9e2-1bb7-4a02-9d19-746da0ef9fd9.jpg)

![Amrit Portrait](https://user-images.githubusercontent.com/90300147/132558030-4493810b-7e65-4847-ab64-cc8b4abca327.jpeg)

**Comment by AmritPatel** [comment]
Basic images have been added. Can now push updates as needed.
